FROM node:18.17-alpine
RUN npm install -g @angular/cli@16.1.8
WORKDIR /app
COPY ./package*.json ./
RUN npm install
COPY . .
EXPOSE 3000
# Ejecutamos el servidor de desarrollo al iniciar el CONTENEDOR
CMD ["npm", "run", "start"]